# Local development overrides
services:
  nayabato-app:
    build:
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - MONGODB_URI=mongodb://mongodb:27017/nayabato
      
  # Enable debugging tools
  mongo-express:
    image: docker.io/library/mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - nayabato-network
